version: '3.8'
services:

  wordpress:
    image: 'wordpress'
    ports:
      - '${PUB_PORT}:80'
    env_file: 
      - .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
    volumes:
      - wordpress:/var/www/html
      - ./install.php:/usr/src/wordpress/wp-admin/install.php
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
  
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 300M
        limits:
          cpus: '0.5'
          memory: 500M

volumes:
  wordpress:
  mysql:
